name: Update publications monthly

on:
  schedule:
    - cron: '0 6 1 * *'  # 06:00 UTC on the 1st of each month
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt

      - name: Update publications from Google Scholar
        env:
          SCHOLAR_USER_ID: ''  # optional override; otherwise read from _config.yml
        run: |
          python scripts/update_publications.py

      - name: Commit and push if changed
        run: |
          git config user.name "Rajeev Jain"
          git config user.email "rajeeja@gmail.com"
          if ! git diff --quiet; then
            git add _data/citations.csv
            git commit -m "chore(ci): monthly publications refresh from Google Scholar"
            git push origin HEAD:master
          else
            echo "No changes to commit"
          fi
